# Automatically generated by configure - do not modify

all:
SRC_PATH=/home/sp24/femu
TARGET_DIRS=x86_64-softmmu
GDB=/usr/bin/gdb
SUBDIRS= contrib/plugins
PYTHON=/home/sp24/femu/build-femu/pyvenv/bin/python3 -B
MKVENV_ENSUREGROUP=/home/sp24/femu/build-femu/pyvenv/bin/python3 -B /home/sp24/femu/python/scripts/mkvenv.py ensuregroup  --online
GENISOIMAGE=
MESON=/home/sp24/femu/build-femu/pyvenv/bin/meson
NINJA=/usr/bin/ninja
EXESUF=
TCG_TESTS_TARGETS= x86_64-softmmu
